name: vllm

channels:
  - pytorch
  - nvidia

dependencies:
  - python=3.10
  - pytorch=2.3.0
  # - pytorch
  - torchvision
  - torchaudio
  - pytorch-cuda=12.1
  # - pytorch-cuda=12.4
  # - nvidia/label/cuda-12.1.0::cuda
  # - nvidia/label/cuda-12.1.0::cuda-nvcc
  # - conda-forge::gxx_linux-64=12.2
  # - conda-forge::cudnn

# ENV vars
# export TMPDIR='/var/tmp'
# export CUDA_HOME=$CONDA_PREFIX
# export CUDA_CUDART_LIBRARY=$CONDA_PREFIX/lib/libcudart.so
# export LD_LIBRARY_PATH=$CONDA_PREFIX/lib:$LD_LIBRARY_PATH

